# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_question(object):
    def setupUi(self, question):
        question.setObjectName("question")
        question.resize(400, 300)
        self.label = QtWidgets.QLabel(question)
        self.label.setGeometry(QtCore.QRect(50, 20, 321, 91))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(question)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 541, 41))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(question)
        self.lineEdit.setGeometry(QtCore.QRect(50, 130, 231, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(question)
        self.pushButton.setGeometry(QtCore.QRect(290, 130, 81, 41))
        self.pushButton.setObjectName("pushButton")
        self.heart = QtWidgets.QLabel(question)
        self.heart.setGeometry(QtCore.QRect(40, 190, 99, 71))
        self.heart.setText("")
        self.heart.setObjectName("heart")
        self.heart.setPixmap(QtGui.QPixmap(r"heart.jpg"))
        self.heart.setScaledContents(True)
        self.icecream = QtWidgets.QLabel(question)
        self.icecream.setGeometry(QtCore.QRect(240, 200, 99, 81))
        self.icecream.setText("")
        self.icecream.setObjectName("icecream")
        self.icecream.setPixmap(QtGui.QPixmap(r"icecream.jpg"))
        self.icecream.setScaledContents(True)

        self.retranslateUi(question)
        self.pushButton.clicked.connect(question.click_comfirm)
        QtCore.QMetaObject.connectSlotsByName(question)

    def retranslateUi(self, question):
        _translate = QtCore.QCoreApplication.translate
        question.setWindowTitle(_translate("question", "小问题"))
        self.label.setText(_translate("question", "冰冰酱和薇姬芬在一起的日子是"))
        self.label_2.setText(_translate("question", "（输入格式：YYYYMMDD）："))
        self.pushButton.setText(_translate("question", "确认"))
