# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wrong.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import wrong
import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 50, 221, 61))
        self.label.setObjectName("label")
        self.wrong = QtWidgets.QLabel(Form)
        self.wrong.setGeometry(QtCore.QRect(200, 130, 151, 120))
        self.wrong.setText("")
        self.wrong.setObjectName("wrong")
        self.wrong.setPixmap(QtGui.QPixmap(r"angry.jpg"))
        self.wrong.setScaledContents(True)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "错啦"))
        self.label.setText(_translate("Form", "错啦，请重新输入！"))


class wrong(QtWidgets.QMainWindow,Ui_Form):
    def __init__(self):
        super(wrong, self).__init__()
        self.setupUi(self)


app = QtWidgets.QApplication(sys.argv)
window = wrong()
window.show()
sys.exit(app.exec_())